from .json_to_python import (
    NAV_OPS_CONFIG,
    MENU_OPS_CONFIG,
    OPS_CONFIG,
    TEAM_TABLE_CONFIG,
    PARTICIPANT_TABLE_CONFIG,
    TEAM_MODEL_CONFIG,
    PARTICIPANT_MODEL_CONFIG,
    TEXT_COLOR_MAP,
)
