CONFIG = {
    "select_operation": {
        "is_menu": True,
        "is_dependency": False,
        "is_pre_op": False,
        "has_ctrlc_escape": False,
        "nav_options": None,
        "display": {
            "title": "Operation Selection",
            "menu_text": None,
            "screen_prompt": "What operation would you like to perform?",
            "action_message": None,
        },
        "dependency_order": None,
    },
    "select_team": {
        "is_menu": True,
        "is_dependency": True,
        "is_pre_op": True,
        "has_ctrlc_escape": False,
        "nav_options": None,
        "display": {
            "title": "Team Selection",
            "menu_text": None,
            "screen_prompt": "What team would you like to work with?",
            "action_message": None,
        },
        "dependency_order": None,
    },
    "select_participant": {
        "is_menu": True,
        "is_dependency": True,
        "is_pre_op": True,
        "has_ctrlc_escape": False,
        "nav_options": None,
        "display": {
            "title": "Participant Selection",
            "menu_text": None,
            "screen_prompt": "What participant would you like to work with?",
            "action_message": None,
        },
        "dependency_order": None,
    },
    "select_agent": {
        "is_menu": True,
        "is_dependency": True,
        "is_pre_op": True,
        "has_ctrlc_escape": False,
        "nav_options": None,
        "display": {
            "title": "Free Agent Selection",
            "menu_text": None,
            "screen_prompt": "What free agent would you like to work with?",
            "action_message": None,
        },
        "dependency_order": None,
    },
    "create_team": {
        "is_menu": False,
        "is_dependency": False,
        "is_pre_op": False,
        "has_ctrlc_escape": True,
        "nav_options": None,
        "display": {
            "title": "New Team",
            "menu_text": "Create a New Team",
            "screen_prompt": "Submit a response for each of the requested details.",
            "action_message": "Team created.",
        },
        "dependency_order": None,
    },
    "create_participant": {
        "is_menu": False,
        "is_dependency": False,
        "is_pre_op": False,
        "has_ctrlc_escape": True,
        "nav_options": None,
        "display": {
            "title": "New Team Member",
            "menu_text": "Create a New Team Member",
            "screen_prompt": "Submit a response for each of the requested details.",
            "action_message": "Participant created.",
        },
        "dependency_order": {
            "select_team": 1,
            "select_agent": 0,
            "select_participant": 0,
            "assign_team_id": 2,
            "select_operation": 0,
        },
    },
    "add_free_agent_to_team": {
        "is_menu": False,
        "is_dependency": False,
        "is_pre_op": False,
        "has_ctrlc_escape": False,
        "nav_options": None,
        "display": {
            "title": "Add Free Agent",
            "menu_text": "Add Free Agent to Team",
            "screen_prompt": None,
            "action_message": "Participant added to team.",
        },
        "dependency_order": {
            "select_team": 1,
            "select_agent": 2,
            "select_participant": 0,
            "assign_team_id": 0,
            "select_operation": 0,
        },
    },
    "assign_team_id": {
        "is_menu": False,
        "is_dependency": True,
        "is_pre_op": False,
        "has_ctrlc_escape": False,
        "nav_options": None,
        "display": None,
        "dependency_order": {
            "select_team": 1,
            "select_agent": 0,
            "select_participant": 2,
            "assign_team_id": 0,
            "select_operation": 0,
        },
    },
    "remove_participant": {
        "is_menu": False,
        "is_dependency": False,
        "is_pre_op": False,
        "has_ctrlc_escape": False,
        "nav_options": None,
        "display": {
            "title": "Remove Participant",
            "menu_text": "Remove Participant from Team",
            "screen_prompt": None,
            "action_message": "Participant removed from team.",
        },
        "dependency_order": {
            "select_team": 1,
            "select_agent": 0,
            "select_participant": 2,
            "assign_team_id": 0,
            "select_operation": 0,
        },
    },
    "delete_participant": {
        "is_menu": False,
        "is_dependency": False,
        "is_pre_op": False,
        "has_ctrlc_escape": False,
        "nav_options": None,
        "display": {
            "title": "Delete Participant",
            "menu_text": "Delete Participant Record",
            "screen_prompt": None,
            "action_message": "Participant deleted.",
        },
        "dependency_order": {
            "select_team": 1,
            "select_agent": 0,
            "select_participant": 2,
            "assign_team_id": 0,
            "select_operation": 0,
        },
    },
    "delete_team": {
        "is_menu": False,
        "is_dependency": False,
        "is_pre_op": False,
        "has_ctrlc_escape": False,
        "nav_options": None,
        "display": {
            "title": "Delete Team",
            "menu_text": "Delete Team Record",
            "screen_prompt": None,
            "action_message": "Team deleted - All participants made free agents.",
        },
        "dependency_order": {
            "select_team": 1,
            "select_agent": 0,
            "select_participant": 0,
            "assign_team_id": 0,
            "select_operation": 0,
        },
    },
    "update_participant_first_name": {
        "is_menu": False,
        "is_dependency": False,
        "is_pre_op": False,
        "has_ctrlc_escape": True,
        "nav_options": None,
        "display": {
            "title": "Update First Name",
            "menu_text": "Update Participant First Name",
            "screen_prompt": "Submit the participant's new first name.",
            "action_message": "Participant first name updated.",
        },
        "dependency_order": {
            "select_team": 1,
            "select_agent": 0,
            "select_participant": 2,
            "assign_team_id": 0,
            "select_operation": 3,
        },
    },
    "update_participant_last_name": {
        "is_menu": False,
        "is_dependency": False,
        "is_pre_op": False,
        "has_ctrlc_escape": True,
        "nav_options": None,
        "display": {
            "title": "Update Last Name",
            "menu_text": "Update Participant Last Name",
            "screen_prompt": "Submit the participant's new last name.",
            "action_message": "Participant last name updated.",
        },
        "dependency_order": {
            "select_team": 1,
            "select_agent": 0,
            "select_participant": 2,
            "assign_team_id": 0,
            "select_operation": 3,
        },
    },
    "update_team_name": {
        "is_menu": False,
        "is_dependency": False,
        "is_pre_op": False,
        "has_ctrlc_escape": True,
        "nav_options": None,
        "display": {
            "title": "Update Name",
            "menu_text": "Update Team Name",
            "screen_prompt": "Submit the team's new name.",
            "action_message": "Team name updated.",
        },
        "dependency_order": {
            "select_team": 1,
            "select_agent": 0,
            "select_participant": 0,
            "assign_team_id": 0,
            "select_operation": 0,
        },
    },
    "return_to_main": {
        "is_menu": False,
        "is_dependency": True,
        "is_pre_op": False,
        "has_ctrlc_escape": False,
        "nav_options": {
            "visibility": lambda open_menu_count: open_menu_count > 1,
            "format": "nope",
            "selectors": ("c",),
        },
        "display": {
            "title": None,
            "menu_text": "Clear All Selections and Return to Main Menu",
            "screen_prompt": None,
            "action_message": None,
        },
        "dependency_order": None,
    },
    "quit_program": {
        "is_menu": False,
        "is_dependency": False,
        "is_pre_op": False,
        "has_ctrlc_escape": False,
        "nav_options": {
            "visibility": lambda open_menu_count: open_menu_count > 0,
            "format": "angry",
            "selectors": ("x", "q"),
        },
        "display": {
            "title": "Exit Application",
            "menu_text": "Exit the Application",
            "screen_prompt": None,
            "action_message": None,
        },
        "dependency_order": None,
    },
}
